version: '3.3'

services:
    app:
        container_name: app
        build:
            context: .
            args:
                REGISTRY: ''
        depends_on:
            - 'nats'
        env_file:
            - .env
        environment:
            - NATS_URL=nats://meditor_nats:4222
        ports:
            - '8080:8080'

    nats:
        container_name: stan
        # locked to version used in meditor-deployments
        image: nats-streaming:0.15.1
        ports:
            - '4222:4222'
